[package]
name = "flipstargamer/clsecom"
description = "A client and server communicator"
license = "MIT"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]