[package]
name = "flipstargamer/clsecom"
description = "A client and server communicator"
license = "MIT"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"