name: docs.yaml

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Builds Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
          node-version: "14"
      - run: npm i -g moonwave@latest
      - name: Deploy
      run: |
        moonwave build --publish